### ISSUE TITLE
dktoolr can't locate darky cart

### ISSUE THREAD

**Issue by sh00tthec0re** [ToughkidDev/DKToolr#1]
I'm using the Darky cart with a Panasonic A1ST Turbo-R.  I've updated the firmware to 1.03.

The dkstatus, dkconfig and modified game ROMs all seem to work with the cart properly, but when I make changes in dkconfig and try to save them to Slot 0 of the cart with dktoolr, it tells me "Can't find Darky Cart."

![1](https://user-images.githubusercontent.com/49319761/155283730-a2c01d17-96e4-4dbf-83ca-a9d0e8e84ad0.jpg)
![2](https://user-images.githubusercontent.com/49319761/155283727-7ba07259-8740-4f7f-9f24-98a48821c744.jpg)

**Comment by ToughkidDev** [comment]
I tested it with the same settings like the picture above.

Slot 1 - Turbo-R ST Mega Flash Rom SCC+ SD
Slot 2- Darky
Test clip here - https://youtu.be/iYgcyZL0XxI

GoodLuck!

**Comment by sh00tthec0re** [comment]
Do you have any suggestions on what I can do?  I'm also finding that some games like SD Snatcher don't produce audio.

Should I revert the firmware to 1.02?  Is my Darky cart defective?  I've tried swapping Darky to Slot 1 and it doesn't make a difference.

Here's a video:
https://youtu.be/wrFWZY9Rjq0

**Comment by ToughkidDev** [comment]
OK.  I have a question.
Yesterday "DKToolr 0 /s" didn't work properly, but today your video seems to be working. Is that correct?   
Is it solved by putting slot 1?
If you are still getting the error in slot 2, then there seems to be a problem with your MSX slot.
Please test it and reply.

**Comment by sh00tthec0re** [comment]
Please check the video I posted again. At 1:56 - I still get the "Can't find Darky Cart." message with "dktoolr 0 /s".  It is the same no matter if the Darky is in Slot 1 or Slot 2.  SD Snatcher audio doesn't work with the cart in either slot too.

I also tried downgrading the firmware 1.02 but it didn't make any difference.

Other Darky-enhanced games are working fine though - I tried Usas and Zanac and they sound great!

Thank you for your help.

**Comment by ToughkidDev** [comment]
I will review your bug report again and analyze the problem.
See you soon.

**Comment by ToughkidDev** [comment]
I tried to fix the suspicious part here. 
https://github.com/ToughkidDev/DKToolr/blob/main/test/DKToolrTestInitTurboR_20220224.COM

Please download & test it on your Turbo-R. 
I will release the full version when problems are identified.

One more thing - If your MSX is booting on R800 turbo mode, turn it off and run SD-SNATCHER. It automatically turns on R800 mode.

**Comment by sh00tthec0re** [comment]
Thanks for the new build of dktoolr.com

I just tried it out, but I still get the same "Can't find Darky Cart" message.

**Comment by ToughkidDev** [comment]
A few confirmations please.

1. Please test it on a model other than TurboR and let me know the result.
2. Are you booting in R800 high-speed mode when booting from MegaFlashRom SCC+ SD?

**Comment by sh00tthec0re** [comment]
Answers:

1) I'm sorry, but my TurboR is the only MSX computer I have access to.  The MSX is a very rare computer in the United States and any MSX computer here has to be imported from another country.

2) It looks like the computer initially boots the MegaFlashRom cart in low-speed Z80 mode, but then switches to R800 high-speed mode when NEXTOR.SYS loads up.  I can hold down the 1 key to force boot into low-speed Z80 and MSX-DOS, but then it won't let me access the Darkly files on the SD card - Drive B says Not Ready.

**Comment by ToughkidDev** [comment]
All right.   
I'll try to find the problem by making your environment the same.
Thank you.

**Comment by sh00tthec0re** [comment]
Thank you so much for your help.

**Comment by ToughkidDev** [comment]
I've tested it in every environment I have and nevertheless tweaked a few things.
After testing the file below, if the same problem still occurs, it is worth suspecting that your Darky is defective.
https://github.com/ToughkidDev/DKToolr/blob/main/test/DKToolrTestInitTurboR_20220226.COM
Good Luck!

**Comment by sh00tthec0re** [comment]
I tried the new dktoolr build, and something interesting is happening.

If I run the new dktoolr immediately after running darkycfg then I get the "Can't find Darky Cart" error.  But if I run dkstatus and then run dktoolr after that then the tool works correctly.

Here's a video showing you what I mean.
https://youtu.be/w0Goe4WolCY

**Comment by ToughkidDev** [comment]
I figured out the problem.
It seems that DARKY is not initialized because there is a problem with shutdown in the latest version of DARKYCFG.
There is no big difference, so until a new version is released, it seems that the problem can be solved by using the old version of DarkyCFG.    
Cheers!

**Comment by sh00tthec0re** [comment]
Ah that certainly makes sense!

One more question for you-do you know why I’m not getting any sound at all when I use the Darky with SD Snatcher? There’s some footage of what it’s doing on my first YouTube clip.

**Comment by ToughkidDev** [comment]
Since the SD-Snatcher for DARKY is a rom image made for a cartridge with scc+ built-in, it does not consider various usage environments. ( https://youtu.be/KtfttQaMUV4 )
If I can afford it, I'll look into it to get it running in the environment you're using.
Have a good weekend.

**Comment by sh00tthec0re** [comment]
That makes sense. Hopefully I’ll be able to buy my own Darky-enhanced SD Snatcher cart one day. 

Thank you for all your help - I really appreciate it. Have a great weekend!
